name: InfObjects
main: org.spout.infobjects.InfObjectsPlugin
version: 0.0.1
author: SpoutDev
commands:
    iwgo:
       description: Place an iWGO
       usage: /iwgo name [force]
       permission: infobject.iwgo
     reloadiwgos
       description: Reload the iWGOs
       usage: /reloadiwgos
       permission: infobject.reload

permissions:
    infobject.iwgo:
        description: Allows to place an iWGO
        default: op
    infobject.reload:
       description: Allows to reload the iWGO
       default: op
